apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: webapp
          image: ghcr.io/anumario/webapp-cicd:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /hello
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /hello
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

